/*
 * This source file was generated by the Gradle 'init' task
 */
package csc216.a.map.in.a.tree;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
}
